### PR TITLE
Support nested inline styles and escaping them with '\'

### PR DESCRIPTION
**Pull request by laino**
Adds support for nested inline styles like

`[bold red]{bold and red [green]{bold and green} bold and red again}`

as well as escaping control characters: 

`[red]{all this \} is red}`.

### CODE REVIEW

**Comment by laino** [comment]
I just realized I obviously shouldn't reproduce the backslash escape sequence in the resulting string.

**Comment by laino** [comment]
The second commit fixes that. I also added a test case to check for that specifically.

**Comment by 75lb** [comment]
Hi, I started reviewing this - useful work, thanks. Does everything work as expected on Linux and Windows too?

**Comment by laino** [comment]
Yes. Built on Linux and tested on Windows as well.

**Comment by 75lb** [comment]
there is one breaking change.. This input when feed into the current version:

```
> console.log(ansi.format('[bold]{AA'))
[bold]{AA
```

..now produces different output in your version: 

```
> console.log(ansi.format('[bold]{AA'))
AA
```

Is stripping all but `AA` strictly necessary? What if I didn't want that?

**Comment by laino** [comment]
Right now?

```
console.log(ansi.format('\\[bold]{AA'))
[bold]{AA
```

However the previous commit changes it so that all opening brackets without matching closing brackets are now treated as literals, restoring the old behavior.

**Comment by laino** [comment]
The most recent commit fixes a case where backslash escapes would get removed too early, causing the escaped sequence to get treated as markup in nested markup.

```
[red]{[red]{\\[green]{red\\}}}
```

**Comment by laino** [comment]
@75lb ping.

All old test-cases pass without changes and it should behave exactly like the old version, except for the added functionality of course.

**Comment by laino** [comment]
@75lb ping.

I've been using this extensively for some time now. Very confident it works as advertised...

**Comment by 75lb** [comment]
hi @laino.. where are you using this library, in command-line-usage? 

To avoid re-inventing wheels, i'm considering updating command-line-usage to use [chalk template literals](https://github.com/chalk/chalk#tagged-template-literal) instead of `ansi.format` for formatting. It already supports nesting, would that suit you? 

An example of usage: 

```js
const sections = [
  {
    header: 'Example App',
    content: 'Generates something {green.underline very {red.bold important}}'
  }
]
```

**Comment by 75lb** [comment]
Chalk solution released in [command-line-usage v5.0.0](https://github.com/75lb/command-line-usage/releases/tag/v5.0.0).

This module (ansi-escape-sequences) will eventually be deprecated.

**Pull request closed without merging**
