### PR TITLE
Types

### PR DESCRIPTION
**Pull request by cancerberoSgx**
type definitions for typescript projects. Dependencies updated

### CODE REVIEW

**Comment by 75lb** [comment]
thanks, but should these types live in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

**Comment by cancerberoSgx** [comment]
I don't think in general the types should be inside the library if it is small and the author wants to maintain them ;)
DefinitelyTyped is more for very big projects which authors don't want ot maintain types so they are maintained by third parties, examples: node.js, express, etc... 
If you ask me I could put the types in DefinitelyTyped, but IMO we want type definitions inside the library if possible so users don't need to install extra @type/ packages that probably are out-of sync. Thanks.

**Comment by 75lb** [comment]
I appreciate this PR but I don't want to maintain Typescript code, sorry about that. 

Several of my other modules have types defined in DefinitelyTyped. I even learned some basic Typescript myself recently so I could update one of the declaration files. Please submit these typings to DefinitelyTyped.

**Comment by cancerberoSgx** [comment]
ok, is understandable, thanks and sorry for the inconvenience

**Pull request closed without merging**
